### ISSUE TITLE
Vignettes give warning

### ISSUE THREAD

**Issue by antaldaniel** [rOpenGov/retroharmonize#12]
Hi Pyry, I am not sure if you changed these vignette settings, but I get this with Afrobarometer (and I think with Arab, too), but strangely not with Eurobarometer. 

* checking re-building of vignette outputs ... WARNING
Warning: Error(s) in re-building vignettes:
--- re-building ‘afrobarometer.Rmd’ using rmarkdown
Warning in engine$weave(file, quiet = quiet, encoding = enc) :

**Comment by pitkant** [comment]
Vignettes had this error already before I pushed any commits to GitHub and 8637b5d checks show the same errors also. I used --no-build-vignettes locally to check everything else but vignettes. I couldn't rebuild arabbarometer-vignette anyway since I do not have Arab Barometer files on my local environment.

**Comment by antaldaniel** [comment]
I added into system.file all data that is needed for this vignette, so they should build locally.  Strange, because the eurobarometer vignette passed with the same settings, and now I do not see this problem appearing again.   Right now the package seems to be passing OK. I am waiting for some minor corrections from @shaibani  and then I think that this can be a minor release.
